[phases.setup]
nixPkgs = ["jdk17"]

[phases.install]
cmds = ["chmod +x gradlew"]

[phases.build]
cmds = ["./gradlew clean bootJar --no-daemon"]

[phases.start]
cmd = "java -Dserver.port=$PORT -Xmx512m -Xms256m -Xshare:off -jar build/libs/*.jar"