[phases.setup]
nixPkgs = ['...', 'jdk17']

[phases.install]
cmds = ['chmod +x gradlew']

[phases.build]
cmds = ['./gradlew clean bootJar --no-daemon']

[start]
cmd = 'java -Dserver.port=$PORT -jar build/libs/*.jar'
